# WEBSITE
title: internet home of ada luong
description: The personal website of @adaluong.
first_name: Ada
last_name: Luong
url: https://adaluong.github.io
url: https://adaluong.me 

# BLOG
blog_name: blog posts
blog_description: an experiment in writing
permalink: /blog/:title/

# JEKYLL SETTINGS

# markdown and syntax highlights
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# includes and excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor

# jekyll plugins
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-minifier
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-link-attributes
  - jemoji
  - jekyll_picture_tag

# responsive images
picture:
  source: "assets/img/"
  output: "assets/img/resized/"
  suppress_warnings: true
  disabled: false # speed up site builds when working on something else

# optional features
enable_darkmode:            true
enable_tooltips:            false

# library versions
bootstrap:
  version: "4.5.2"
  integrity:
    css: "sha512-MoRNloxbStBcD8z3M/2BmnT+rg4IsMxPkXaGh2zD6LGNNFE80W3onsAhRcMAMrSoyWL9xD7Ert0men7vR8LUZg=="
    js: "sha512-M5KW3ztuIICmVIhjSqXe01oV2bpe248gOxqmlcYrEzAvws7Pw3z6BK0iGbrwvdrUQUhi3eXgtxp5I8PDo9YfjQ=="
fontawesome:
  version: "5.14.0"
  integrity: "sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
jquery:
  version: "3.5.1"
  integrity: "sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
mathjax:
  version: "3.1.2"
mdb:
  version: "4.19.1"
  integrity:
    css: "sha512-RO38pBRxYH3SoOprtPTD86JFOclM51/XTIdEPh5j8sj4tp8jmQIx26twG52UaLi//hQldfrh7e51WzP9wuP32Q=="
    js: "sha512-Mug9KHKmroQFMLm93zGrjhibM2z2Obg9l6qFG2qKjXEXkMp/VDkI4uju9m4QKPjWSwQ6O2qzZEnJDEeCw0Blcw=="
popper:
  version: "2.4.4"
  integrity: "sha512-eUQ9hGdLjBjY3F41CScH3UX+4JDSI9zXeroz7hJ+RteoCaY+GP/LDoM8AO+Pt+DRFw3nXqsjh9Zsts8hnYv8/A=="
